export const SET_FIRST_NUMBER = 'SET_FIRST_NUMBER'
export const SET_SECOND_NUMBER = 'SET_SECOND_NUMBER'
export const SET_THIRD_NUMBER = 'SET_THIRD_NUMBER'
export const SET_METHOD = 'SET_METHOD'
export const CALCULATE = 'CALCULATE'
export const SUM = '+'
export const MULTIPLY = '*'
