import {
  SET_FIRST_NUMBER,
  SET_SECOND_NUMBER,
  SET_THIRD_NUMBER,
  SET_METHOD,
  CALCULATE
} from './calcluatorConstants'

export {
  SET_FIRST_NUMBER,
  SET_SECOND_NUMBER,
  SET_THIRD_NUMBER,
  SET_METHOD,
  CALCULATE
}
